config/routes.rb
Sampleapp::Application.routes.draw do
resources :users do
    member do
      get :following, :followers
    end
end

resources :microposts do
  member do
    post :vote_up
  end
end

  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy, :vote_up]
  resources :relationships, :only => [:create, :destroy]
  resources :image, :only => [:create, :destroy]
  

  
  
  match '/', :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
    match '/signup',  :to => 'users#new'
    match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

    root :to => 'pages#home'

end

app/views/pages/about.html.erb
<font color="#FFFFFF">
    <h1><strong><font size="5">About Us</font></strong></h1>
    <p><font size="3">
      Wir als goodnews.de moechten euch die neuesten und die unerreichbaren Nachrichten und Wissen anbieten.
    </font><br />
    
    <h3><font color="#FFFFFF"><strong>Goodnews</strong></font></h3><font size="3"> bietet die beste Moeglichkeit, zu entdecken, was es in
    der Welt Neues gibt.</font>

<br /><font size="3">Goodnews ist ein Informationsnetzwerk, welches dir in Echtzeit die neuesten Informationen zu Themen
liefert, die dich interessieren. Suche einfach nach oeffentlichen Posts, die fuer dich von Interesse sind
und folge der Konversation.
<br />
Im Herzen Goodnew's befinden sich winzige Informationspartikel, die sich Micros nennen. Jeder Micro ist 140
Zeichen lang. Aber lasse dich nicht von der Kuerze eines Micros taeuschen. Du kannst auch auf schmalem Raum
vieles mitteilen. Jeder Micro ist mit einem detaillierten Fenster verbunden, welches weiterfuehrende
Informationen enthaelt und integrierte Medien sichtbar macht. Du kannst einen Micro verwenden, um eine
Aussage zu machen. Siehe es in Aktion.
Du musst nicht unbedingt mircoposten, um einen Wert in Goodnews zu sehen.
<br /><br />


Du musst keine Webseite gestalten, um das Internet geniessen zu koennen und genauso musst du nicht
microposten, um Goodnews zu geniessen. Du hast stets Zugang zu den Stimmen und Informationen die dich
interessieren, ob du hundertmal am Tag micropostest oder nie. Du kannst etwas zu diesem Informationsfluss
beitragen oder Informationen schlicht konsumieren. Manche Leute microposten nie, sie nutzen Goodnews als
Nachrichtenquelle fuer Informationen, die sie interessieren.
</font>
<br />  
    </p>
</font>

app/views/pages/contact.html.erb
<font color="#FFFFFF">
    <h1><strong><font size="5">Contact</font></strong></h1>
    <font size="4">
    Hochschule fuer Wirtschaft und Recht
    Campus Schoeneberg<br>
    Badensche Strasse 52<br>
    10825 Berlin<br><br> 
    Studiengang; Wirtschaftsinformatik<br>
    Fach; Webanwendungen<br>
    Gruppe; Goodnews.de<br>
    Gruppenmitglieder; <br>
    Tung Nguyen, Suzan Holmquist , Martin Koltermann
    
    </font>
</font>

app/views/pages/home.html.erb
<% if signed_in? %>
  <table class="front" summary="For signed-in users">
    <tr>
      <td class="main">
        <h1 class="micropost">Teil die neuesten Meldungen!</h1>
        <%= render 'shared/micropost_form' %>
         <%= render 'shared/feed' %>
      </td>
      <td class="sidebar round">
        <%= render 'shared/user_info' %>
        <%= render 'shared/stats' %>
      </td>
    </tr>
  </table>
<% else %>
  <div align= center>
  <p><%= link_to "Registrieren", signup_path, :class => "Registrieren_button round" %></p>
  <p><%= link_to "Sign in", signin_path, :class => "signin_button round" %></p>
  <p><%= link_to "About", about_path, :class => "about_button round" %></p>
  <p><%= link_to "Contact", contact_path, :class => "contact_button round" %></p>
  <p><%= link_to "Help", help_path, :class => "help_button round" %></p>
  </div>
<% end %>