config/routes.rb
Sampleapp::Application.routes.draw do
resources :users do
    member do
      get :following, :followers
    end
end

resources :microposts do
  member do
    post :vote_up
  end
end

  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy, :vote_up]
  resources :relationships, :only => [:create, :destroy]
  resources :image, :only => [:create, :destroy]
  

  
  
  match '/', :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
    match '/signup',  :to => 'users#new'
    match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

    root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer>
 
</footer>

app/views/layouts/_header.html.erb
<header>
 <% logo = image_tag("neu.jpg", :alt => "Goodnews", :class => "round") %>
  <%= link_to logo, root_path %> 
  <nav class="round">
    <ul>
     <% if signed_in? %>
      <li><strong><font size="4"><%= link_to "Home", root_path %></font></font></strong></li>
      <li><strong><font size="4"><%= link_to "Users", users_path %></font></font></strong></li>
      <li><strong><font size="4"><%= link_to "Profile", current_user %></font></font></strong></li>
      <li><strong><font size="4"><%= link_to "Settings", edit_user_path(current_user) %></font></font></strong></li>
      <li><strong><font size="4"><%= link_to "About", about_path %></font></font></strong></li>
      <li><strong><font size="4"><%= link_to "Contact", contact_path %></font></font></strong></li>
      <li><strong><font size="4"><%= link_to "Help", help_path %></font></font></strong></li>
      <% end %>
      <% if signed_in? %>
      <li><strong><font size="4"><%= link_to "Sign out", signout_path, :method => :delete %></font></font></strong></li>
      
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
            <%= debug(params) if Rails.env.development? %>

    </div>
  </body>
</html>